<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="configuration.ACF_testcases" tests="16" time="1228.217" ignored="63" failures="8" timestamp="04 Nov 2017 02:50:14 GMT" skipped="0" hostname="remote-wkstn3" errors="0">
  <testcase name="create_an_acf_data_type_decimal_field_type_text" time="94.393" classname="configuration.ACF_testcases">
    <failure type="java.lang.AssertionError" message="expected [8] but found [4]">
      <![CDATA[java.lang.AssertionError: expected [8] but found [4]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at configuration.ACFPage.validateUpdates(ACFPage.java:229)
	at configuration.ACF_testcases.create_an_acf_data_type_decimal_field_type_text(ACF_testcases.java:247)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- create_an_acf_data_type_decimal_field_type_text -->
  <testcase name="create_a_new_acf_without_group_name" time="79.758" classname="configuration.ACF_testcases"/>
  <testcase name="return_to_acf_main_page_from_add_page" time="34.504" classname="configuration.ACF_testcases"/>
  <testcase name="create_a_new_acf_without_screens" time="70.930" classname="configuration.ACF_testcases"/>
  <testcase name="create_a_new_acf_without_field_name" time="82.686" classname="configuration.ACF_testcases"/>
  <testcase name="create_an_acf_data_type_varchar_field_type_Wysiwyg_editor" time="97.762" classname="configuration.ACF_testcases">
    <failure type="java.lang.AssertionError" message="expected [8] but found [4]">
      <![CDATA[java.lang.AssertionError: expected [8] but found [4]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at configuration.ACFPage.validateUpdates(ACFPage.java:229)
	at configuration.ACF_testcases.create_an_acf_data_type_varchar_field_type_Wysiwyg_editor(ACF_testcases.java:175)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- create_an_acf_data_type_varchar_field_type_Wysiwyg_editor -->
  <testcase name="create_an_acf_data_type_int_field_type_text" time="90.315" classname="configuration.ACF_testcases">
    <failure type="java.lang.AssertionError" message="expected [4] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [4] but found [2]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at configuration.ACFPage.validateUpdates(ACFPage.java:229)
	at configuration.ACF_testcases.create_an_acf_data_type_int_field_type_text(ACF_testcases.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- create_an_acf_data_type_int_field_type_text -->
  <testcase name="create_a_new_acf_without_field_instructions" time="78.690" classname="configuration.ACF_testcases"/>
  <testcase name="click_cancel_in_acf_add_page" time="34.399" classname="configuration.ACF_testcases"/>
  <testcase name="create_an_acf_data_type_varchar_field_type_text_area" time="94.279" classname="configuration.ACF_testcases">
    <failure type="java.lang.AssertionError" message="expected [8] but found [4]">
      <![CDATA[java.lang.AssertionError: expected [8] but found [4]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at configuration.ACFPage.validateUpdates(ACFPage.java:229)
	at configuration.ACF_testcases.create_an_acf_data_type_varchar_field_type_text_area(ACF_testcases.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- create_an_acf_data_type_varchar_field_type_text_area -->
  <testcase name="create_an_acf_data_type_decimal_field_type_select" time="96.697" classname="configuration.ACF_testcases">
    <failure type="java.lang.AssertionError" message="expected [8] but found [4]">
      <![CDATA[java.lang.AssertionError: expected [8] but found [4]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at configuration.ACFPage.validateUpdates(ACFPage.java:229)
	at configuration.ACF_testcases.create_an_acf_data_type_decimal_field_type_select(ACF_testcases.java:284)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- create_an_acf_data_type_decimal_field_type_select -->
  <testcase name="delete_acf_from_database" time="12.109" classname="configuration.ACF_testcases"/>
  <testcase name="create_an_acf_data_type_varchar_field_type_text" time="91.780" classname="configuration.ACF_testcases">
    <failure type="java.lang.AssertionError" message="expected [8] but found [4]">
      <![CDATA[java.lang.AssertionError: expected [8] but found [4]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at configuration.ACFPage.validateUpdates(ACFPage.java:229)
	at configuration.ACF_testcases.create_an_acf_data_type_varchar_field_type_text(ACF_testcases.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- create_an_acf_data_type_varchar_field_type_text -->
  <testcase name="create_an_acf_data_type_int_field_type_select" time="96.239" classname="configuration.ACF_testcases">
    <failure type="java.lang.AssertionError" message="expected [8] but found [4]">
      <![CDATA[java.lang.AssertionError: expected [8] but found [4]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at configuration.ACFPage.validateUpdates(ACFPage.java:229)
	at configuration.ACF_testcases.create_an_acf_data_type_int_field_type_select(ACF_testcases.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- create_an_acf_data_type_int_field_type_select -->
  <testcase name="create_a_new_acf_without_field_label" time="79.012" classname="configuration.ACF_testcases"/>
  <testcase name="create_an_acf_data_type_varchar_field_type_select" time="94.664" classname="configuration.ACF_testcases">
    <failure type="java.lang.AssertionError" message="expected [8] but found [4]">
      <![CDATA[java.lang.AssertionError: expected [8] but found [4]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at configuration.ACFPage.validateUpdates(ACFPage.java:229)
	at configuration.ACF_testcases.create_an_acf_data_type_varchar_field_type_select(ACF_testcases.java:212)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- create_an_acf_data_type_varchar_field_type_select -->
  <testcase name="empty_name_field_in_permission_categories_edit_page" classname="access.PermissionCategoriesEdit_TestCases">
    <skipped/>
  </testcase> <!-- empty_name_field_in_permission_categories_edit_page -->
  <testcase name="empty_controller_name_field_in_permission_categories_edit_page" classname="access.PermissionCategoriesEdit_TestCases">
    <skipped/>
  </testcase> <!-- empty_controller_name_field_in_permission_categories_edit_page -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="tearDown" classname="Utility.TestBase">
    <skipped/>
  </testcase> <!-- tearDown -->
  <testcase name="update_template_type_to_previous" classname="layout.TemplatesEdit_testcases">
    <skipped/>
  </testcase> <!-- update_template_type_to_previous -->
  <testcase name="update_template_type" classname="layout.TemplatesEdit_testcases">
    <skipped/>
  </testcase> <!-- update_template_type -->
  <testcase name="open_workflow_page" classname="login.Dashboard_TestCases">
    <skipped/>
  </testcase> <!-- open_workflow_page -->
  <testcase name="update_message_client_field" classname="library.MessagesEdit_Testcases">
    <skipped/>
  </testcase> <!-- update_message_client_field -->
  <testcase name="update_message_clientname_to_previous_client" classname="library.MessagesEdit_Testcases">
    <skipped/>
  </testcase> <!-- update_message_clientname_to_previous_client -->
  <testcase name="empty_permission_category_field_in_permissions_edit_page" classname="access.PemissionsEdit_TestCases">
    <skipped/>
  </testcase> <!-- empty_permission_category_field_in_permissions_edit_page -->
  <testcase name="empty_name_field_in_permissions_edit_page" classname="access.PemissionsEdit_TestCases">
    <skipped/>
  </testcase> <!-- empty_name_field_in_permissions_edit_page -->
</testsuite> <!-- configuration.ACF_testcases -->
