<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="library.Messages_TestCases" tests="1" time="42.732" ignored="9" failures="1" timestamp="26 Jul 2017 15:42:50 GMT" skipped="0" hostname="remote-wkstn3" errors="0">
  <testcase name="create_a_new_message" time="42.732" classname="library.Messages_TestCases">
    <failure type="java.lang.AssertionError" message="expected [CODA - Messages - Add] but found [CODA - Error]">
      <![CDATA[java.lang.AssertionError: expected [CODA - Messages - Add] but found [CODA - Error]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at library.MessagesPage.clickAddMessageButton(MessagesPage.java:35)
	at library.Messages_TestCases.create_a_new_message(Messages_TestCases.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- create_a_new_message -->
  <testcase name="click_cancel_message_button" classname="library.Messages_TestCases">
    <skipped/>
  </testcase> <!-- click_cancel_message_button -->
  <testcase name="clone_message" classname="library.Messages_TestCases">
    <skipped/>
  </testcase> <!-- clone_message -->
  <testcase name="create_testdata_message" classname="library.Messages_TestCases">
    <skipped/>
  </testcase> <!-- create_testdata_message -->
  <testcase name="create_a_new_message_without_a_message_name" classname="library.Messages_TestCases">
    <skipped/>
  </testcase> <!-- create_a_new_message_without_a_message_name -->
  <testcase name="create_publish_message" classname="library.Messages_TestCases">
    <skipped/>
  </testcase> <!-- create_publish_message -->
  <testcase name="create_a_new_message_without_brand" classname="library.Messages_TestCases">
    <skipped/>
  </testcase> <!-- create_a_new_message_without_brand -->
  <testcase name="create_a_new_message_without_clientname" classname="library.Messages_TestCases">
    <skipped/>
  </testcase> <!-- create_a_new_message_without_clientname -->
  <testcase name="delete_message_from_db" classname="library.Messages_TestCases">
    <skipped/>
  </testcase> <!-- delete_message_from_db -->
  <testcase name="CCL_AE_Failtocreate_message" classname="library.Messages_TestCases">
    <skipped/>
  </testcase> <!-- CCL_AE_Failtocreate_message -->
</testsuite> <!-- library.Messages_TestCases -->
