<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="PERMISSION ACTIONS TESTCASES"
           tests="8"
           failures="1"
           errors="0"
           skipped="0"
           time="302.405">
  <properties />
            <testcase name="create_a_new_permission_action" time="57.080" classname="access.PermissionActions_TestCases">
                <failure type="java.lang.AssertionError"
                  message="expected [CODA - Permission Actions] but found [CODA - PermissionActions - Add]"
              >
<![CDATA[java.lang.AssertionError: expected [CODA - Permission Actions] but found [CODA - PermissionActions - Add]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:513)
  org.testng.Assert.assertEqualsImpl(Assert.java:135)
  org.testng.Assert.assertEquals(Assert.java:116)
  org.testng.Assert.assertEquals(Assert.java:190)
  org.testng.Assert.assertEquals(Assert.java:200)
  access.PermissionActionsAddPage.clickSave(PermissionActionsAddPage.java:60)
  access.PermissionActions_TestCases.create_a_new_permission_action(PermissionActions_TestCases.java:19)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  org.testng.TestRunner.privateRun(TestRunner.java:756)
  org.testng.TestRunner.run(TestRunner.java:610)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
  org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
  org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
  org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
  java.util.concurrent.FutureTask.run(FutureTask.java:266)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:745)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="returm_to_permission_actions_main_page" time="27.141" classname="access.PermissionActions_TestCases" />
                <testcase name="click_cancel_in_permission_action_add_page" time="36.248" classname="access.PermissionActions_TestCases" />
                <testcase name="delete_permission_action_from_database" time="2.185" classname="access.PermissionActions_TestCases" />
                <testcase name="create_a_duplicate_permission_action" time="46.791" classname="access.PermissionActions_TestCases" />
                <testcase name="create_a_new_permission_action_without_controller_name" time="44.999" classname="access.PermissionActions_TestCases" />
                <testcase name="create_a_new_permission_action_without_permission" time="44.051" classname="access.PermissionActions_TestCases" />
                <testcase name="create_a_new_permission_action_without_name" time="43.910" classname="access.PermissionActions_TestCases" />
      
</testsuite>
