<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="TEMPLATES TESTCASES"
           tests="9"
           failures="1"
           errors="0"
           skipped="0"
           time="483.453">
  <properties />
            <testcase name="create_a_new_template_channel_email_type_communication" time="52.859" classname="layout.Templates_TestCases">
                <failure type="java.lang.AssertionError"
                  message="expected [Carnival Corporation &amp; PLC] but found [The Lacek Group - Test]"
              >
<![CDATA[java.lang.AssertionError: expected [Carnival Corporation & PLC] but found [The Lacek Group - Test]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:513)
  org.testng.Assert.assertEqualsImpl(Assert.java:135)
  org.testng.Assert.assertEquals(Assert.java:116)
  org.testng.Assert.assertEquals(Assert.java:190)
  org.testng.Assert.assertEquals(Assert.java:200)
  layout.TemplatesPage.validateUpdates(TemplatesPage.java:174)
  layout.Templates_TestCases.create_a_new_template_channel_email_type_communication(Templates_TestCases.java:24)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  org.testng.TestRunner.privateRun(TestRunner.java:756)
  org.testng.TestRunner.run(TestRunner.java:610)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
  org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
  org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
  org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
  java.util.concurrent.FutureTask.run(FutureTask.java:266)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:745)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="create_a_new_template_channel_web_type_communication" time="85.350" classname="layout.Templates_TestCases" />
                <testcase name="create_a_new_template_channel_email_type_message" time="79.621" classname="layout.Templates_TestCases" />
                <testcase name="create_a_new_template_without_a_name" time="43.563" classname="layout.Templates_TestCases" />
                <testcase name="create_a_new_template_without_a_type" time="42.261" classname="layout.Templates_TestCases" />
                <testcase name="create_a_new_template_channel_web_type_message" time="77.561" classname="layout.Templates_TestCases" />
                <testcase name="delete_template_from_db" time="17.964" classname="layout.Templates_TestCases" />
                <testcase name="create_a_new_template_without_a_channel" time="44.557" classname="layout.Templates_TestCases" />
                <testcase name="create_a_new_template_without_a_clientname" time="39.717" classname="layout.Templates_TestCases" />
      
</testsuite>
