<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="SERIES TESTCASES"
           tests="6"
           failures="1"
           errors="0"
           skipped="0"
           time="200.315">
  <properties />
            <testcase name="create_a_new_series_without_brand" time="42.506" classname="library.Series_Testcases">
                <failure type="java.lang.AssertionError"
                  message="expected [] but found [carsales]"
              >
<![CDATA[java.lang.AssertionError: expected [] but found [carsales]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:513)
  org.testng.Assert.assertEqualsImpl(Assert.java:135)
  org.testng.Assert.assertEquals(Assert.java:116)
  org.testng.Assert.assertEquals(Assert.java:190)
  org.testng.Assert.assertEquals(Assert.java:200)
  library.SeriesPage.validateUpdates(SeriesPage.java:229)
  library.Series_Testcases.create_a_new_series_without_brand(Series_Testcases.java:83)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  org.testng.TestRunner.privateRun(TestRunner.java:756)
  org.testng.TestRunner.run(TestRunner.java:610)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
  org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
  org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
  org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
  java.util.concurrent.FutureTask.run(FutureTask.java:266)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:745)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="create_a_new_serie_without_clientname" time="33.411" classname="library.Series_Testcases" />
                <testcase name="delete_series_from_db" time="2.452" classname="library.Series_Testcases" />
                <testcase name="click_cancel_series_button" time="24.411" classname="library.Series_Testcases" />
                <testcase name="create_a_new_series_without_seriesnname" time="34.168" classname="library.Series_Testcases" />
                <testcase name="create_a_new_serie" time="63.367" classname="library.Series_Testcases" />
      
</testsuite>
