<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="CAMPAIGN TESTCASES"
           tests="8"
           failures="1"
           errors="0"
           skipped="0"
           time="282.057">
  <properties />
            <testcase name="create_a_new_campaign_without_series" time="37.510" classname="library.Campaigns_Testcases">
                <failure type="java.lang.AssertionError"
                  message="expected [1] but found [0]"
              >
<![CDATA[java.lang.AssertionError: expected [1] but found [0]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:513)
  org.testng.Assert.assertEqualsImpl(Assert.java:135)
  org.testng.Assert.assertEquals(Assert.java:116)
  org.testng.Assert.assertEquals(Assert.java:190)
  org.testng.Assert.assertEquals(Assert.java:200)
  library.CampaignPage.validateUpdates(CampaignPage.java:241)
  library.Campaigns_Testcases.create_a_new_campaign_without_series(Campaigns_Testcases.java:115)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  org.testng.TestRunner.privateRun(TestRunner.java:756)
  org.testng.TestRunner.run(TestRunner.java:610)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
  org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
  org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
  org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
  java.util.concurrent.FutureTask.run(FutureTask.java:266)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:745)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="create_a_new_campaign" time="78.785" classname="library.Campaigns_Testcases" />
                <testcase name="create_a_new_campaign_without_campaignname" time="33.113" classname="library.Campaigns_Testcases" />
                <testcase name="create_a_new_campaign_without_program" time="40.810" classname="library.Campaigns_Testcases" />
                <testcase name="click_cancel_button_in_campaign_add_page" time="19.644" classname="library.Campaigns_Testcases" />
                <testcase name="delete_campaign_from_db" time="3.572" classname="library.Campaigns_Testcases" />
                <testcase name="create_a_new_campaign_without_brand" time="44.735" classname="library.Campaigns_Testcases" />
                <testcase name="create_a_new_campaign_without_clientname" time="23.888" classname="library.Campaigns_Testcases" />
      
</testsuite>
