<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="R90JDQN3" name="TEMPLATES EDIT TESTCASES" tests="16" failures="12" timestamp="22 Dec 2016 19:50:06 GMT" time="717.692" errors="0">
  <testcase name="update_template_brand" time="68.707" classname="layout.TemplatesEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [0] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [2]
	at layout.TemplatesPage.validateUpdates(TemplatesPage.java:157)
	at layout.TemplatesEdit_testcases.update_template_brand(TemplatesEdit_testcases.java:21)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- update_template_brand -->
  <testcase name="update_template_brand_to_previous" time="62.618" classname="layout.TemplatesEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1]
	at layout.TemplatesPage.validateUpdates(TemplatesPage.java:157)
	at layout.TemplatesEdit_testcases.update_template_brand_to_previous(TemplatesEdit_testcases.java:35)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- update_template_brand_to_previous -->
  <testcase name="update_template_name" time="41.413" classname="layout.TemplatesEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [edit_template_test_010] but found [CUNARD]">
      <![CDATA[java.lang.AssertionError: expected [edit_template_test_010] but found [CUNARD]
	at layout.TemplatesPage.validateUpdates(TemplatesPage.java:163)
	at layout.TemplatesEdit_testcases.update_template_name(TemplatesEdit_testcases.java:48)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- update_template_name -->
  <testcase name="update_template_name_to_previous" time="40.058" classname="layout.TemplatesEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [edit_template_test_01] but found [CUNARD]">
      <![CDATA[java.lang.AssertionError: expected [edit_template_test_01] but found [CUNARD]
	at layout.TemplatesPage.validateUpdates(TemplatesPage.java:163)
	at layout.TemplatesEdit_testcases.update_template_name_to_previous(TemplatesEdit_testcases.java:61)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- update_template_name_to_previous -->
  <testcase name="update_template_channel" time="39.804" classname="layout.TemplatesEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [Web] but found []">
      <![CDATA[java.lang.AssertionError: expected [Web] but found []
	at layout.TemplatesPage.validateUpdates(TemplatesPage.java:178)
	at layout.TemplatesEdit_testcases.update_template_channel(TemplatesEdit_testcases.java:74)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- update_template_channel -->
  <testcase name="update_template_channel_to_previous" time="36.64" classname="layout.TemplatesEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [Email] but found []">
      <![CDATA[java.lang.AssertionError: expected [Email] but found []
	at layout.TemplatesPage.validateUpdates(TemplatesPage.java:178)
	at layout.TemplatesEdit_testcases.update_template_channel_to_previous(TemplatesEdit_testcases.java:87)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- update_template_channel_to_previous -->
  <testcase name="update_template_clientname" time="39.779" classname="layout.TemplatesEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [DuPont] but found [351]">
      <![CDATA[java.lang.AssertionError: expected [DuPont] but found [351]
	at layout.TemplatesPage.validateUpdates(TemplatesPage.java:141)
	at layout.TemplatesEdit_testcases.update_template_clientname(TemplatesEdit_testcases.java:126)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- update_template_clientname -->
  <testcase name="update_template_clientname_to_previous" time="37.591" classname="layout.TemplatesEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [Carnival Corporation &amp;amp; PLC] but found [351]">
      <![CDATA[java.lang.AssertionError: expected [Carnival Corporation & PLC] but found [351]
	at layout.TemplatesPage.validateUpdates(TemplatesPage.java:141)
	at layout.TemplatesEdit_testcases.update_template_clientname_to_previous(TemplatesEdit_testcases.java:140)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- update_template_clientname_to_previous -->
  <testcase name="select_button_save_in_template_page" time="31.925" classname="layout.TemplatesEdit_testcases"/>
  <testcase name="select_button_cancel_in_template_page" time="28.985" classname="layout.TemplatesEdit_testcases"/>
  <testcase name="inactivate_template" time="38.043" classname="layout.TemplatesEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [INACTIVE] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [INACTIVE] but found [0]
	at layout.TemplatesPage.validateUpdates(TemplatesPage.java:183)
	at layout.TemplatesEdit_testcases.inactivate_template(TemplatesEdit_testcases.java:175)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- inactivate_template -->
  <testcase name="activate_template" time="37.967" classname="layout.TemplatesEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [ACTIVE] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [ACTIVE] but found [0]
	at layout.TemplatesPage.validateUpdates(TemplatesPage.java:183)
	at layout.TemplatesEdit_testcases.activate_template(TemplatesEdit_testcases.java:188)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- activate_template -->
  <testcase name="set_template_workflow_to_draft" time="31.612" classname="layout.TemplatesEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [DRAFT] but found [ACTIVE]">
      <![CDATA[java.lang.AssertionError: expected [DRAFT] but found [ACTIVE]
	at layout.TemplatesPage.validateUpdates(TemplatesPage.java:188)
	at layout.TemplatesEdit_testcases.set_template_workflow_to_draft(TemplatesEdit_testcases.java:200)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- set_template_workflow_to_draft -->
  <testcase name="set_template_workflow_to_approved" time="31.865" classname="layout.TemplatesEdit_testcases">
    <failure type="java.lang.AssertionError" message="expected [APPROVED] but found [ACTIVE]">
      <![CDATA[java.lang.AssertionError: expected [APPROVED] but found [ACTIVE]
	at layout.TemplatesPage.validateUpdates(TemplatesPage.java:188)
	at layout.TemplatesEdit_testcases.set_template_workflow_to_approved(TemplatesEdit_testcases.java:212)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- set_template_workflow_to_approved -->
  <testcase name="archive_template" time="15.689" classname="layout.TemplatesEdit_testcases"/>
  <testcase name="restore_template" time="26.571" classname="layout.TemplatesEdit_testcases"/>
</testsuite> <!-- TEMPLATES EDIT TESTCASES -->
